### PR TITLE
Fix minion subsession creation on Pi 0.68+

### LINKED ISSUE #12: Seems to be broken with pi >=0.68
I just updated form ~0.67 to 70 and something is broken, because my main cannot spawn minions. 

Will investigate, just noting it here.

> The "path" argument must be of type string. Received undefined

### PR DESCRIPTION
**Pull request by tunnckoCore**
## Summary
- pass explicit cwd/agentDir settings into minion DefaultResourceLoader
- reuse the same SettingsManager for minion AgentSession creation
- let createAgentSession use Pi default tool selection instead of passing legacy Tool objects
- update SDK mocks for explicit agent dir lookup

## Testing
- npm test
- npm run typecheck *(fails locally: missing @mariozechner/pi-ai and @mariozechner/pi-agent-core type deps under pnpm strict node_modules)*

closes #12

### CODE REVIEW

File: src/subsessions/manager.ts [hunk 1]
```diff
@@ -106,7 +105,6 @@ export class SubsessionManager {
     const { session } = await createAgentSession({
       cwd: this.cwd,
       model: parentModel,
-      tools: createCodingTools(this.cwd),
```
Comment (tunnckoCore) [inline src/subsessions/manager.ts:109]: my agent said that it would use the default tools anyway. it's fine if you want to limit it strictly to something, but i don't think we need to.

**Comment by tunnckoCore** [comment]
It works, i'm using it locally.

**Review by kalindudc — APPROVED** [review]
Thanks for fixing this 🚀
